### ISSUE TITLE
not an issue - but an important note

### ISSUE THREAD

**Issue by 8secz-johndpope** [ananay/apple-auth#18]
https://forums.developer.apple.com/thread/129047
I spent a few weeks troubleshooting keys to verify signature - this is a bit of a gotcha as it can all seem to work and then it breaks.

**Comment by 8secz-johndpope** [comment]
related https://github.com/wwenj/Sign-in-with-Apple-for-node/issues/1

**Comment by ananay** [comment]
Hi @8secz-johndpope, thanks for opening up an issue about this. I don't have the signature verification implemented as of now but I'll let people at Apple know about this issue.

Thanks!
