### ISSUE TITLE
Apple Developer Domain Association - outdated in SETUP.md

### ISSUE THREAD

**Issue by nesro** [ananay/apple-auth#28]
The docs https://github.com/ananay/apple-auth/blob/master/SETUP.md mention a need for verifying your site with `.well-known/apple-developer-domain-association.txt` file.

According to this comment https://developer.apple.com/forums/thread/119616?answerId=646593022#646593022 (and my experience too), it is no longer possible to verify your site with this file.

SETUP.md should be updated and this part should be removed.

**Comment by ananay** [comment]
Done!
