### ISSUE TITLE
Do i have to pay 90 $/year to apple to use their Auth ?

### ISSUE THREAD

**Issue by romain130492** [ananay/apple-auth#29]
I just wondering Do i have to pay 90 $ to apple to use their Auth ?
@L1qu1d1c3 @ananay 
thanks!

**Comment by ananay** [comment]
Hi @Romain130492, my guess would be no, but I'm unaware what the free account is capable of. If you would like to give it a try - head over to the (setup.md)[https://github.com/ananay/apple-auth/blob/master/SETUP.md] file. If any of the options on the webpages are missing then you will probably have to get a developer account. I won't be surprised if you will need to, though.

Good luck!

**Comment by SeriousMonk** [comment]
Yes, in order to use the Sign In With Apple feature you must have an Apple Developer Membership.
