### ISSUE TITLE
AppleAuth Error - An error occurred while getting response from Apple's servers: Error: Request failed with status code 400

### ISSUE THREAD

**Issue by daixianceng** [ananay/apple-auth#31]
AppleAuth Error - An error occurred while getting response from Apple's servers: Error: Request failed with status code 400

**Comment by Rami-K-Youssef** [comment]
You can try modifying apple-auth.js inside your node_modules to log that error. I its frustrating because usually the response contains more information regarding the error.

**Comment by ananay** [comment]
Sorry for the delay, and thanks for filing this. I'll be adding this to the repository soon.

**Comment by iway1** [comment]
would be great to show the error that apple returns (IE the "invalid_client", "invalid_grant"). Also, some of the error bodies from apple pass an additional message as well which would be helpful.

**Comment by trust2065** [comment]
In the source code of `apple-auth.js`.
Find the `catch` in `accessToken` method `reject("AppleAuth Error - An error occurred while getting response from Apple's servers: " + response);` but it's not too useful to debug.
Modify it and print `response.response.data` you get the error and error description

ex:
```
data: {
  error: 'invalid_grant', 
  error_description: 'redirect_uri mismatch. The code was not issued to https://lxxx.'
}     
```
