### ISSUE TITLE
new AppleAuth - third parameter is undocumented

### ISSUE THREAD

**Issue by devnm21** [ananay/apple-auth#38]
Maybe the third parameter is recently added and not documented.

But I found the usage in one of @ananay example repo:
https://github.com/ananay/apple-auth-example/blob/92d2d1a5568dfded4156a4d5ed3cc5e0b3206096/src/app.js#L9C33-L9C91

**Comment by ananay** [comment]
Thanks for pointing that out! Wrote this a while back when someone requested that you should be able to pass the private key as text. I will go ahead and change it to be only text (and just get rid of the parameter), as contents of the private key file can always be read using `fs`. Right now, even if you put the third parameter as a `file` it still reads it as text so better to just get rid of the param.
