### ISSUE TITLE
TeamID leak in screenshot

### ISSUE THREAD

**Issue by identitymonk** [ananay/apple-auth#4]
Hi @ananay 

You masked you teamID except in screenshot https://user-images.githubusercontent.com/5569219/59017608-95539980-8861-11e9-9605-86c509cd7d68.png.

Regards

**Comment by ananay** [comment]
Hi @identitymonk, thanks for pointing that out. The team ID is not sensitive information as it cannot be used to create provisioning profiles and will not pass verification by Apple even if it is provided to them. You can reverse engineer apps and find the Team ID for any app.

**Comment by identitymonk** [comment]
Hi @ananay 

you masked it in other screen shots so inconsistency sounded weird.

JF

**Comment by ananay** [comment]
Hi @identitymonk 

For the sake of consistency, I've masked the Team ID and updated the setup.md file!

Thanks.
