### ISSUE TITLE
Submit app to app store?

### ISSUE THREAD

**Issue by L1qu1d1c3** [ananay/apple-auth#7]
Hello!

First of all, great module! But I do have some issues that your documentation does not cover:

Does the application have to be submitted to the app store for review in order for it to allow Sign In with Apple?
I did all the steps necessary but when I access the login page, it just gives me an error that states:
Your request could not be completed because of an error. Please try again later. 

Cheers.

**Comment by ananay** [comment]
Hi @L1qu1d1c3, you don't need to submit anything to the app store for approval!

If you're 100% sure that your configuration is correct, a reason you *might* be getting that error is because your URL may not be "https". If not, please install an SSL cert to your domain and make sure the config has "https".

Also, thank you for appreciating my module!

**Comment by L1qu1d1c3** [comment]
hi @ananay ,

I finally got it working, my com.* name was wrong in the url.
One thing I haven’t been able to test out is what Apple sends back to the /auth url when you successfully log in. I tried parsing everything, including back/frontend, but its as if the redirect url wasn’t getting any parameteres.
Would you kindly post an example of your express server and how you process the response from Apple?

Thank you!

**Comment by ananay** [comment]
Hi @L1qu1d1c3,

I've made an entire example repository: https://github.com/ananay/apple-auth-example
This should help you with understanding!
This exact same example is also running on my website: https://apple.ananay.dev

**Comment by L1qu1d1c3** [comment]
Hi @ananay ,

I tested it out on your website and what I'm seeing is that apple only really returns tokens. But can you ever create an user/email/name from this information? No, right?

I'm trying further, but it sucks that "sign in with apple" has no sandbox mode...

Cheers
